# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'IsshoMeshi' do
  use_frameworks!
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod 'RxSwift',    '~> 2.0'
  pod 'RxCocoa',    '~> 2.0'
  pod 'Hakuba'
  pod 'Sapporo'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
end

