# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'IsshoMeshi' do
  use_frameworks!
  pod 'Alamofire', '3.5.0'
  pod 'SwiftyJSON'
  pod 'Hakuba'
  pod 'Sapporo'
  pod 'Kingfisher', '2.6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end
